// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH6G2O80pmHMspX6sTh7XO0vaAfn4aXT8',
    appId: '1:150180241306:web:fcc4591abe73fe36f9a423',
    messagingSenderId: '150180241306',
    projectId: 'chat-application-naidu199',
    authDomain: 'chat-application-naidu199.firebaseapp.com',
    storageBucket: 'chat-application-naidu199.appspot.com',
    measurementId: 'G-B28Z1QC92N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvhejdh_mcW38xjF7yvk2pyPtnk_cWLRk',
    appId: '1:150180241306:android:b7a957ebf13dd866f9a423',
    messagingSenderId: '150180241306',
    projectId: 'chat-application-naidu199',
    storageBucket: 'chat-application-naidu199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAYW1bsER_umDfgKnhBrXRweAt8a4iMME',
    appId: '1:150180241306:ios:a25df4067d2dab56f9a423',
    messagingSenderId: '150180241306',
    projectId: 'chat-application-naidu199',
    storageBucket: 'chat-application-naidu199.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAYW1bsER_umDfgKnhBrXRweAt8a4iMME',
    appId: '1:150180241306:ios:a25df4067d2dab56f9a423',
    messagingSenderId: '150180241306',
    projectId: 'chat-application-naidu199',
    storageBucket: 'chat-application-naidu199.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH6G2O80pmHMspX6sTh7XO0vaAfn4aXT8',
    appId: '1:150180241306:web:fe870945587fd0d4f9a423',
    messagingSenderId: '150180241306',
    projectId: 'chat-application-naidu199',
    authDomain: 'chat-application-naidu199.firebaseapp.com',
    storageBucket: 'chat-application-naidu199.appspot.com',
    measurementId: 'G-S67QCPC96N',
  );
}
